# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_dataloader_string.ipynb.

# %% auto 0
__all__ = ['Stringloader']

# %% ../../nbs/03_dataloader_string.ipynb 6
from langchain.document_loaders.base import BaseLoader, Document

from fastcore.all import *


# %% ../../nbs/03_dataloader_string.ipynb 7
class Stringloader(BaseLoader):
    """Load string variable.


    Args:
        text: String variable that contains the text.

        metadata: Metadata Information
    """
    
    def __init__(
        self,
        text: str,
        metadata: Optional[str] = None,
        autodetect_encoding: bool = False,
    ):
        """Initialize with file path."""
        self.text = text
        self.metadata = metadata

    def load(self) -> List[Document]:
        """Load from file path."""
        metadata = {"source": self.metadata}
        return [Document(page_content=self.text, metadata=metadata)]
