# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/langchain_tutorials',
                'doc_host': 'https://Dmaturana81.github.io',
                'git_url': 'https://github.com/Dmaturana81/langchain_tutorials',
                'lib_path': 'langchain_tutorials'},
  'syms': {'langchain_tutorials.core': {'langchain_tutorials.core.foo': ('core.html#foo', 'langchain_tutorials/core.py')}}}
