# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_extracting.ipynb.

# %% auto 0
__all__ = ['msg', 'prompt', 'Extract']

# %% ../nbs/02_extracting.ipynb 6
from pydantic import BaseModel, Field
from langchain.prompts import ChatPromptTemplate


from langchain.chains.openai_functions import (
    create_openai_fn_chain,
    create_structured_output_chain,
)

from langchain.chat_models import ChatOpenAI
from fastcore.all import *
import json

# %% ../nbs/02_extracting.ipynb 7
msg = 'Show the health of client foo'

# %% ../nbs/02_extracting.ipynb 9
class Extract(BaseModel):
    """Tool to extract the intent and the attribute of it"""
    intent:str = Field(default=None,
                    description="Refers to what the human needs.",
                    )
    attribute:str = Field(...,description="From who or where needs the information.")
    

# %% ../nbs/02_extracting.ipynb 11
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a world class algorithm to extract information from the message. You are trainned to get the intent as well as further attributes."),
        ("human", "Use the given format to extract the information from the human message.'\n{input}"),
        ("human", "Tip: Make sure to answer in the correct format"),
    ]
)
